# Generated by Django 3.0.7 on 2020-07-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20200714_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
