# Generated by Django 3.0.7 on 2020-07-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_auto_20200716_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='r_id',
            new_name='restaurant',
        ),
    ]
