# Generated by Django 3.0.7 on 2020-07-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_auto_20200716_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
