# Generated by Django 3.0.7 on 2020-07-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('State_no', models.AutoField(primary_key=True, serialize=False)),
                ('State_Name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('City_No', models.AutoField(primary_key=True, serialize=False)),
                ('City_Name', models.CharField(max_length=40, unique=True)),
                ('State_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.StateModel')),
            ],
        ),
    ]
